markdown: kramdown
highlighter: rouge
sass:
  style: compressed


repository: https://github.com/lsy643/lsy643.github.io

defaults:
  -
    scope:
      path: "_docs"
      type: "docs"
    values:
      layout: "docs"

  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "news_item"


collections:
  docs:
    permalink: /:collection/:path/
    output: true

  posts:
    permalink: /news/:year/:month/:day/:title/
    output: true


exclude:
  - .gitignore
  - README.md