# Site settings
title: Notes
email: siyuanli.s.c@gmail.com
description: "Notes"
baseurl: ""


# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

